# alacritty.toml
# -----------------------------------------------------------------------------
# Entry point for Alacritty.
# - Uses *single-file* imports for host + theme pointers (active.toml).
# - Pointers are created/updated by bootstrap scripts and are NOT tracked in git.
# -----------------------------------------------------------------------------

[general]
import = [
  "~/.config/alacritty/base.toml",
  "~/.config/alacritty/os.toml",
  "~/.config/alacritty/host.toml",
  "~/.config/alacritty/theme.toml"
  # "~/.config/alacritty/host.d/active.toml",
  # "~/.config/alacritty/theme.d/active.toml"
]

live_config_reload = true
