# -*- conf-toml -*-
# # vim: ft=toml
#
# File: ~/.config/alacrittyalacritty.toml
#

[general]
import = [
  "~/.config/alacritty/base.toml",
  "~/.config/alacritty/os.toml",
  "~/.config/alacritty/host.toml",
  "~/.config/alacritty/theme.toml"
]

live_config_reload = true
