# linux.toml
# -----------------------------------------------------------------------------
# Linux-specific overrides.
# -----------------------------------------------------------------------------

# [terminal]
# shell = { program = "/bin/zsh", args = ["-c", "tmux"] }
